PRISM:
  model_path: "/data/case_level/open_source_model/model/Prism/pytorch_model.bin"
  segmenter: "hest"
  mag: 20
  patch_size: 224
  overlap: 0
  patch_encoder: "virchow"
  slide_encoder: "prism"
  device: "cuda"

CONCH:
  model_path: "/data/case_level/open_source_model/model/conch/pytorch_model.bin"
  mag: 20
  patch_size: 224
  overlap: 0
  device: "cuda"

UNI:
  model_path: "/data/case_level/open_source_model/model/uni/pytorch_model.bin"
  mag: 20
  patch_size: 224
  overlap: 0
  device: "cuda"

TITAN:
  model_path: "/data/case_level/open_source_model/model/Titan/pytorch_model.bin"
  mag: 20
  patch_size: 224
  overlap: 0
  device: "cuda"

Virchow:
  model_path: "/data/case_level/open_source_model/model/Virchow/pytorch_model.bin"
  mag: 20
  patch_size: 224
  overlap: 0
  device: "cuda"