Prism:
  weight_path: "path/to/your/prism/weights.pth"
  segmenter: "hest"
  mag: 20
  patch_size: 224
  overlap: 0
  patch_encoder: "virchow"
  slide_encoder: "prism"

CONCH:
  weight_path: "path/to/your/conch/weights.pth"
  model_param1: value1
  model_param2: value2

UNI:
  weight_path: "path/to/your/uni/weights.pth"
  model_param1: value1
  model_param2: value2

TITAN:
  weight_path: "path/to/your/titan/weights.pth"
  model_param1: value1
  model_param2: value2